server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: dmb-curso  # El nombre de la ruta para enrutar las solicitudes
          uri: lb://ms-curso  # Enviar las solicitudes a dmb-curso a través de Eureka (Load Balancer)
          predicates:
           - Path=/cursos/**
        - id: ms-student  # El nombre de la ruta para enrutar las solicitudes
          uri: lb://ms-student  # Enviar las solicitudes a dmb-curso a través de Eureka (Load Balancer)
          predicates:
            - Path=/estudiantes/**
        - id: ms-matricula  # El nombre de la ruta para enrutar las solicitudes
          uri: lb://ms-matricula  # Enviar las solicitudes a dmb-curso a través de Eureka (Load Balancer)
          predicates:
            - Path=/matriculas/**